export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';

export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER = 'REGISTER'
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_ERASMUS = 'REGISTER_ERASMUS';
export const REGISTER_ERASMUS_START = 'REGISTER_ERASMUS_START';
export const REGISTER_ERASMUS_FAIL = 'REGISTER_ERASMUS_FAIL';
export const REGISTER_ERASMUS_SUCCESS = 'REGISTER_ERASMUS_SUCCESS';

export const NAVBAR_SET_DISPLAY = 'NAVBAR_SET_DISPLAY';

export const FETCH_STUDENT_PROFILE_START = 'FETCH_STUDENT_PROFILE_START';
export const FETCH_STUDENT_PROFILE_SUCCESS = 'FETCH_STUDENT_PROFILE_SUCCESS';
export const FETCH_STUDENT_PROFILE_FAIL = 'FETCH_STUDENT_PROFILE_FAIL';
export const FETCH_STUDENT_PROFILE = 'FETCH_STUDENT_PROFILE';

export const CLEAR_CONNECTION_ERROR = 'CLEAR_CONNECTION_ERROR';
export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const GET_CONNECTION_STATUS = 'GET_CONNECTION_STATUS';
export const GET_CONNECTION_STATUS_START = 'GET_CONNECTION_STATUS_START';
export const GET_CONNECTION_STATUS_SUCCESS = 'GET_CONNECTION_STATUS_SUCCESS';
export const GET_CONNECTION_STATUS_FAIL = 'GET_CONNECTION_STATUS_FAIL';
export const GET_CONNECTIONS = 'GET_CONNECTIONS';
export const GET_CONNECTIONS_SUCCESS = 'GET_CONNECTIONS_SUCCESS';
export const GET_CONNECTIONS_START = 'GET_CONNECTIONS_START';
export const GET_CONNECTIONS_FAIL = 'GET_CONNECTIONS_FAIL';
export const MAKE_CONNECTION = 'MAKE_CONNECTION';
export const ACCEPT_CONNECTION = 'ACCEPT_CONNECTION';
export const ACCEPT_CONNECTION_START = 'ACCEPT_CONNECTION_START';
export const ACCEPT_CONNECTION_SUCCESS = 'ACCEPT_CONNECTION_SUCCESS';
export const ACCEPT_CONNECTION_FAIL = 'ACCEPT_CONNECTION_FAIL';
export const REFUSE_CONNECTION = 'REFUSE_CONNECTION';
export const REFUSE_CONNECTION_START = 'REFUSE_CONNECTION_START';
export const REFUSE_CONNECTION_SUCCESS = 'REFUSE_CONNECTION_SUCCESS';
export const REFUSE_CONNECTION_FAIL = 'REFUSE_CONNECTION_FAIL';

export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';

export const PASSWORDFORGOTTEN_START = 'PASSWORDFORGOTTEN_START';
export const PASSWORDFORGOTTEN_MAIL_SUCCES = 'PASSWORDFORGOTTEN_MAIL_SUCCES';
export const PASSWORDFORGOTTEN_MAIL_FAIL = 'PASSWORDFORGOTTEN_MAIL_FAIL';
export const PASSWORDFORGOTTEN_NEWPASSWORD = 'PASSWORDFORGOTTEN_NEWPASSWORD';
export const PASSWORDFORGOTTEN_NEWPASSWORD_SUCCESS = 'PASSWORDFORGOTTEN_NEWPASSWORD_SUCCESS';
export const PASSWORDFORGOTTEN_NEWPASSWORD_FAIL = 'PASSWORDFORGOTTEN_NEWPASSWORD_FAIL';
export const CLEAR_CONFIRMATION_MESSAGE = 'CLEAR_CONFIRMATION_MESSAGE'
export const CLEAR_ERRORS_AUTH = 'CLEAR_ERRORS_AUTH'

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_START = 'GET_MESSAGES_START';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const SELECT_CHAT = 'SELECT_CHAT';

