export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_USER = 'AUTH_USER';

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'


export const NAVBAR_SET_DISPLAY = 'NAVBAR_SET_DISPLAY';

export const FETCH_STUDENT_PROFILE_START = 'FETCH_STUDENT_PROFILE_START';
export const FETCH_STUDENT_PROFILE_SUCCESS = 'FETCH_STUDENT_PROFILE_SUCCESS';
export const FETCH_STUDENT_PROFILE_FAIL = 'FETCH_STUDENT_PROFILE_FAIL';
export const FETCH_STUDENT_PROFILE = 'FETCH_STUDENT_PROFILE';

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
